name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Abdellahsyani
          template: classic
          base: header, metadata, repositories
          config_timezone: Africa/Casablanca

          plugin_repositories: yes
          plugin_repositories_featured: Abdellahsyani/cpp_projects, Abdellahsyani/MiniShell, Abdellahsyani/3D_game

          config_order: base.header, base.metadata, base.repositories
